/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marcyliano Saputra
 */
public class HomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMotorsport = new javax.swing.JButton();
        btnWrestling = new javax.swing.JButton();
        btnInformasi = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMotorsport.setBorderPainted(false);
        btnMotorsport.setContentAreaFilled(false);
        btnMotorsport.setFocusPainted(false);
        btnMotorsport.addActionListener(this::btnMotorsportActionPerformed);
        getContentPane().add(btnMotorsport, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 143, 110, 260));

        btnWrestling.setContentAreaFilled(false);
        btnWrestling.setFocusPainted(false);
        btnWrestling.addActionListener(this::btnWrestlingActionPerformed);
        getContentPane().add(btnWrestling, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 143, 120, 260));

        btnInformasi.setContentAreaFilled(false);
        btnInformasi.setFocusPainted(false);
        btnInformasi.addActionListener(this::btnInformasiActionPerformed);
        getContentPane().add(btnInformasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 143, 120, 260));

        btnLogout.setBackground(new java.awt.Color(0, 204, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-24.png"))); // NOI18N
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setFocusPainted(false);
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 40, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/WhatsApp Image 2026-06-27 at 15.43.41.jpeg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(814, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMotorsportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotorsportActionPerformed
    MainFrame main = new MainFrame();
    
    main.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnMotorsportActionPerformed

    private void btnWrestlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWrestlingActionPerformed
    MainFrame main = new MainFrame();
    
    main.tampilkanHalamanWrestling();
    
    main.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnWrestlingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      this.dispose(); 
    
    LoginFrame halamanLogin = new LoginFrame();
    halamanLogin.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformasiActionPerformed
    MainFrame main = new MainFrame();
    
    main.tampilkanHalamanInformasi();
    
    main.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnInformasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformasi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMotorsport;
    private javax.swing.JButton btnWrestling;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
